### ISSUE TITLE
what is the delta files for?

### ISSUE THREAD

**Issue by micklexqg** [willylulu/celeba-hq-modified#1]
Hi, thanks for your work,  i wonder  what is the delta files for?
and have you get 1024x1024 images using h5tool.py?

**Comment by micklexqg** [comment]
@willylulu ， thank you, i run the code, but only get 30000 img files. i find that the given image_list.txt is not complete (only with 30000 rows). so how to get the complete txt files which is for 220599 image files?

**Comment by willylulu** [comment]
Please reference this markdown file
https://github.com/aleju/papers/blob/master/neural-nets/Progressive_Growing_of_GANs.md
In summary > how > CelebA-HQ section it says that : 
"They derive from CelebA images a new dataset containing 30k 1024x1024 images of celebrity faces."

I think it's only have 30000 images in celeba-hq. So training with celea-hq is quiet tough.

**Comment by micklexqg** [comment]
@willylulu ，好吧, that is not good。。。thank you！

**Comment by Alalisho** [comment]
hello, i really don't understand how can i convert my dataset celebA to celebA-HQ ,,,, can you help me please? what's the steps?
