### ISSUE TITLE
Excluding the first 7382 images!

### ISSUE THREAD

**Issue by knazeri** [willylulu/celeba-hq-modified#4]
Is there a reason that you are excluding the first 7382 items?
https://github.com/willylulu/celeba-hq-modified/blob/48d26c23234a9ae893fdcf48c9e842f0cd3d0486/h5tool.py#L608

**Comment by willylulu** [comment]
No, it’s totally a mistake. I will fix the bug soon. Thank you for your report.

**Comment by willylulu** [comment]
Fix it
